config/routes.rb
Foodcost::Application.routes.draw do
	root to: 'ingredients#index'
  resources :ingredients
  resources :recipes
  resources :recipe_ingredients, only: [:create, :destroy]
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
	has_many :recipe_ingredients
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

	has_many(
		:recipe_ingredients,
		class_name: "RecipeIngredient",
		foreign_key: :recipe_id,
		primary_key: :id
	)
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ActiveRecord::Base
	belongs_to :recipe
	belongs_to :ingredient
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
	def index
		@ingredients = Ingredient.all
	end

	def new
	end

	def create
		@ingredient = Ingredient.new(ingredient_params)
		if @ingredient.save
			redirect_to ingredients_url
		else
			render :new
		end
	end

	def destroy
		@ingredient = Ingredient.find(params[:id])
		if @ingredient.destroy
			redirect_to ingredients_url
		end
	end

	private

	def ingredient_params
		params.require(:ingredient).permit(:name, :amount, :cost)
	end
end

app/controllers/recipe_ingredients_controller.rb
class RecipeIngredientsController < ApplicationController
	def create
		@recipe_ingredient = RecipeIngredient.new(recipe_ingredient_params)
		if @recipe_ingredient.save
			redirect_to recipe_url(recipe_ingredient_params[:recipe_id])
		end
	end

	def destroy
		@recipe_ingredient = RecipeIngredient.find(params[:id])
		@recipe = @recipe_ingredient.recipe
		if @recipe_ingredient.destroy
			redirect_to recipe_url(@recipe.id)
		end
	end

	private

	def recipe_ingredient_params
		params.require(:recipe_ingredient).permit(:ingredient_id, :recipe_id, :amount)
	end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	def index
		@recipes = Recipe.all
	end

	def show
		@recipe = Recipe.find(params[:id])
		@recipe_ingredients = @recipe.recipe_ingredients
		@ingredients = Ingredient.all
	end

	def create
		@recipe = Recipe.new(recipe_params)
		if @recipe.save
			redirect_to recipe_url(@recipe.id)
		end
	end

	private

	def recipe_params
		params.require(:recipe).permit(:name)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipe_ingredients_helper.rb
module RecipeIngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
	def recipe_cost
		recipe = Recipe.find(params[:id])
		total_cost = 0
		recipe.recipe_ingredients.each do |recipe_ingredient|
			cost_per_gram = (recipe_ingredient.ingredient.cost * 1.0) / recipe_ingredient.ingredient.amount
			total_cost += (recipe_ingredient.amount * cost_per_gram)
		end

		total_cost
	end
end

app/views/ingredients/index.html.erb
<h1>Add New Ingredient</h1>
<form action="<%=ingredients_url %>" method="post">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"
	<label for="ingredient_name">Ingredient</label>
	<input type="text" id="ingredient_name" name="ingredient[name]">
	<br>
	<label for="ingredient_amount">Amount (grams)</label>
	<input type="number" id="ingredient_amount" name="ingredient[amount]" step="any">
	<br>
	<label for="ingredient_cost">Cost</label>
	<input type="number" id="ingredient_cost" name="ingredient[cost]" step="any">
	<br>
	<input type="submit" value="Add Ingredient">
</form>

<h1>Ingredients</h1>
<ul>
	<% @ingredients.each do |ingredient| %>
		<li>
			<ul>
				<li>Ingredient: <%= ingredient.name %></li>
				<li>Cost: <%= ingredient.cost %></li>
				<li>Amount: <%= ingredient.amount %></li>
				<li>Cost per Gram: $<%= (ingredient.cost * 1.0) / ingredient.amount %></li>
				<li><%= button_to "Delete Ingredient", ingredient_url(ingredient.id), method: :delete %>
			</ul>
		</li>
	<% end %>
</ul>

app/views/ingredients/new.html.erb
<form action="<%=ingredients_url%>" method="post">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"
	<label for="ingredient_name">Ingredient</label>
	<input type="text" id="ingredient_name" name="ingredient[name]">
	<br>
	<label for="ingredient_amount">Amount (grams)</label>
	<input type="number" id="ingredient_amount" name="ingredient[amount]">
	<br>
	<label for="ingredient_cost">Cost</label>
	<input type="number" id="ingredient_cost" name="ingredient[cost]">
	<br>
	<input type="submit" value="Add Ingredient">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foodcost</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to "Ingredients", ingredients_url %> | <%= link_to "Recipes", recipes_url %>
<br>
<%= yield %>

</body>
</html>

app/views/recipes/index.html.erb
<h1>Add New Recipe</h1>
<form action="<%= recipes_url %>" method="post">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	<label for="recipe_name">Recipe:</label>
	<input type="text" id="recipe_name" name="recipe[name]">
	<input type="submit" value="Add Recipe">
</form>
<h1>Recipes</h1>
<ul>
	<% @recipes.each do |recipe| %>
		<li><%= link_to recipe.name, recipe_url(recipe.id) %></li>
	<% end %>
</ul>

app/views/recipes/new.html.erb
<form action="<%= recipes_url %>" method="post">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	<label for="recipe_name">Recipe:</label>
	<input type="text" id="recipe_name" name="recipe[name]">
	<input type="submit" value="Add Recipe">
</form>

app/views/recipes/show.html.erb
Total Cost: $<span id="recipe-cost"><%= recipe_cost %></span>
<br>
Number of Units: <input type="number" id="num-of-units">
<br>
Cost Per Unit: $<span id="cost-per-unit"></span>
<br>
Ingredients
<ul>
	<% if @recipe_ingredients %>
		<% @recipe_ingredients.each do |recipe_ingredient| %>
		<% cost_per_gram = (recipe_ingredient.ingredient.cost * 1.0)/recipe_ingredient.ingredient.amount %>
			<li>
				<ul>
					<li>Ingredient: <%= recipe_ingredient.ingredient.name %> <%= button_to "Remove Ingredient", recipe_ingredient_url(recipe_ingredient.id), method: :delete %> </li>
					<li>Amount: <%= recipe_ingredient.amount %> grams</li>
					<!-- <li>Cost/gram: $<%= cost_per_gram %> </li> -->
					<!-- <li>Cost for Recipe: $<%= cost_per_gram * recipe_ingredient.amount %></li> -->
				</ul>
			</li>
		<% end %>
	<% end %>
</ul>
<form action="<%= recipe_ingredients_url %>" method="post">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	<input type="hidden" name="recipe_ingredient[recipe_id]" value="<%= @recipe.id %>">
	<select name="recipe_ingredient[ingredient_id]">
		<% @ingredients.each do |ingredient| %>
			<option value="<%= ingredient.id %>"><%= ingredient.name %></option>
		<% end %> 
	</select>
	<label for="recipe_ingredient_amount">Amount:</label>
	<input type="number" id="recipe_ingredient_amount" name="recipe_ingredient[amount]" step="any">
	<input type="submit" value="Add Ingredient to Recipe"></input>
</form>